[package]
name = "raytracing_p2"
version = "0.1.0"
edition = "2021"
authors = ["Humberto de la Cruz"]

[dependencies]
minifb = "0.27"
rayon = "1.10"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 1
